import { env } from 'cloudflare:workers';
import type { PortalPrincipal } from './portal-auth';

type Job = { id: number; passenger_name: string; phone: string; pickup: string; dropoff: string; pickup_at: string; passengers: number; large_bags: number; small_bags: number; status: string; notes: string };

export async function DriverDashboard({ user, signOutPath }: { user: PortalPrincipal; signOutPath: string }) {
  const result = await env.DB.prepare(`SELECT id,passenger_name,phone,pickup,dropoff,pickup_at,passengers,large_bags,small_bags,status,notes FROM bookings WHERE owner_id=? AND assigned_driver_user_id=? AND status NOT IN ('cancelled','canceled') ORDER BY pickup_at DESC LIMIT 100`).bind(user.ownerId, user.userId).all<Job>();
  return <main className="min-h-screen bg-slate-950 px-5 py-8 text-slate-100"><div className="mx-auto max-w-3xl"><header className="mb-8 flex items-center justify-between border-b border-slate-700 pb-5"><div><p className="text-sm font-semibold uppercase tracking-widest text-amber-400">APX RIDE</p><h1 className="mt-2 text-3xl font-bold">My assigned jobs</h1><p className="mt-1 text-sm text-slate-400">Signed in as {user.email}</p></div><a className="rounded-lg border border-amber-400 px-4 py-2 text-amber-300" href={signOutPath}>Sign out</a></header>{!result.results.length ? <p className="rounded-xl border border-slate-700 bg-slate-900 p-6">No jobs have been assigned to you yet.</p> : <div className="space-y-4">{result.results.map((job) => <article key={job.id} className="rounded-xl border border-slate-700 bg-slate-900 p-5"><div className="flex justify-between gap-4"><h2 className="text-lg font-semibold">{job.pickup} → {job.dropoff}</h2><span className="text-sm uppercase text-amber-300">{job.status}</span></div><p className="mt-2 text-sm text-slate-300">{new Date(job.pickup_at).toLocaleString('en-GB')} · {job.passenger_name} · {job.passengers} passenger(s)</p><p className="mt-1 text-sm text-slate-400">Bags: {job.large_bags} large, {job.small_bags} small</p>{job.phone && <a className="mt-3 inline-block text-amber-300 underline" href={`tel:${job.phone}`}>Call passenger</a>}{job.notes && <p className="mt-3 whitespace-pre-wrap text-sm text-slate-300">{job.notes}</p>}</article>)}</div>}</div></main>;
}
