'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { CalendarDays, Car, CircleUserRound, Gauge, LogOut, Menu, PoundSterling, ShieldCheck, X } from 'lucide-react';
import type { PortalPrincipal } from './portal-auth';

type Job = { assignment_id: number; assignment_status: string; driver_agreed_payment: number; payment_status: string; payment_date: string; payment_notes: string; id: number; passenger_name: string; phone: string; pickup: string; dropoff: string; pickup_at: string; passengers: number; large_bags: number; small_bags: number; fleet_tier: string; notes: string };
type Availability = { id: number; unavailable_date: string; full_day: number; start_time: string; end_time: string; reason: string };
type Workspace = { jobs: Job[]; availability: Availability[]; profile: Record<string, unknown> & { eligibility_reasons?: string[] }; earnings: { total: number; paid: number; outstanding: number } };
const statusLabel = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/(^|\s)\S/g, (letter) => letter.toUpperCase());

export function DriverDashboard({ user, signOutPath, environment }: { user: PortalPrincipal; signOutPath: string; environment: string }) {
  const [data, setData] = useState<Workspace | null>(null); const [tab, setTab] = useState('Dashboard'); const [menu, setMenu] = useState(false); const [error, setError] = useState('');
  const refresh = useCallback(async () => { const response = await fetch('/api/driver-workspace'); const value = await response.json() as Workspace & { error?: string }; if (!response.ok) { setError(value.error || 'Could not load Driver workspace'); return; } setData(value); }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  const nav = [['Dashboard', Gauge], ['My Jobs', Car], ['My Calendar', CalendarDays], ['Availability', CalendarDays], ['My Earnings', PoundSterling], ['Compliance', ShieldCheck], ['Profile', CircleUserRound]] as const;
  return <main className="driver-workspace"><aside className={menu ? 'open' : ''}><header><img src="/apx-logo.png" alt="APX RIDE" /><button onClick={() => setMenu(false)}><X /></button></header><nav>{nav.map(([name, Icon]) => <button key={name} className={tab === name ? 'active' : ''} onClick={() => { setTab(name); setMenu(false); }}><Icon />{name}</button>)}</nav><footer><strong>{user.email}</strong><span>Driver · {environment}</span><a href={signOutPath}><LogOut />Sign out</a></footer></aside><section className="driver-main"><header className="driver-top"><button onClick={() => setMenu(true)}><Menu /></button><div><small>APX RIDE DRIVER</small><h1>{tab}</h1></div><span>{user.email}</span></header>{error && <p className="driver-alert">{error}</p>}{!data ? <p className="driver-empty">Loading secure workspace…</p> : <DriverView tab={tab} data={data} refresh={refresh} />}</section></main>;
}

function DriverView({ tab, data, refresh }: { tab: string; data: Workspace; refresh: () => Promise<void> }) {
  const active = data.jobs.filter((job) => !['COMPLETED','DRIVER_DECLINED','ASSIGNMENT_CANCELLED','CUSTOMER_CANCELLED','NO_SHOW','REASSIGNMENT_REQUIRED','INCIDENT_REPORTED'].includes(job.assignment_status));
  if (tab === 'Dashboard') return <div className="driver-stack"><div className="driver-stats"><article><span>Active jobs</span><strong>{active.length}</strong></article><article><span>Paid earnings</span><strong>£{Number(data.earnings.paid || 0).toFixed(2)}</strong></article><article><span>Outstanding</span><strong>£{Number(data.earnings.outstanding || 0).toFixed(2)}</strong></article></div><section className="driver-card"><h2>Next jobs</h2><JobList jobs={active.slice().sort((a,b) => a.pickup_at.localeCompare(b.pickup_at)).slice(0, 3)} refresh={refresh} /></section></div>;
  if (tab === 'My Jobs') return <section className="driver-card"><h2>My Jobs</h2><p>Only journeys offered or assigned to you are visible.</p><JobList jobs={data.jobs} refresh={refresh} /></section>;
  if (tab === 'My Calendar') return <DriverCalendar jobs={data.jobs.filter((job) => !['DRIVER_DECLINED','ASSIGNMENT_CANCELLED','CUSTOMER_CANCELLED','REASSIGNMENT_REQUIRED'].includes(job.assignment_status))} refresh={refresh} />;
  if (tab === 'Availability') return <AvailabilityView entries={data.availability} refresh={refresh} />;
  if (tab === 'My Earnings') return <section className="driver-card"><h2>My Earnings</h2><p>Only your agreed Driver payment is shown. Customer fares are not included.</p><div className="driver-stats"><article><span>Total completed</span><strong>£{Number(data.earnings.total || 0).toFixed(2)}</strong></article><article><span>Paid</span><strong>£{Number(data.earnings.paid || 0).toFixed(2)}</strong></article><article><span>Pending/approved</span><strong>£{Number(data.earnings.outstanding || 0).toFixed(2)}</strong></article></div><div className="driver-table">{data.jobs.filter((job) => job.assignment_status === 'COMPLETED').map((job) => <div key={job.assignment_id}><span>{new Date(job.pickup_at).toLocaleDateString('en-GB')} · APX-{String(job.id).padStart(5,'0')}</span><b>£{Number(job.driver_agreed_payment).toFixed(2)}</b><em>{statusLabel(job.payment_status)}{job.payment_date ? ` · ${job.payment_date}` : ''}</em></div>)}</div></section>;
  if (tab === 'Compliance') return <ComplianceView profile={data.profile} />;
  return <section className="driver-card"><h2>Profile</h2><dl className="driver-profile"><div><dt>Name</dt><dd>{String(data.profile?.full_name || 'Not recorded')}</dd></div><div><dt>Phone</dt><dd>{String(data.profile?.phone || 'Not recorded')}</dd></div><div><dt>Licensing authority</dt><dd>{String(data.profile?.licensing_authority || 'Not recorded')}</dd></div><div><dt>Vehicle</dt><dd>{String(data.profile?.registration || 'Not assigned')} · {String(data.profile?.make_model_colour || '')}</dd></div></dl><p>Contact the Admin to change verified licensing or vehicle information.</p></section>;
}

function JobList({ jobs, refresh }: { jobs: Job[]; refresh: () => Promise<void> }) {
  if (!jobs.length) return <p className="driver-empty">No jobs in this view.</p>;
  return <div className="driver-jobs">{jobs.map((job) => <article key={job.assignment_id}><header><div><small>APX-{String(job.id).padStart(5,'0')}</small><h3>{job.pickup} → {job.dropoff}</h3></div><span>{statusLabel(job.assignment_status)}</span></header><p>{new Date(job.pickup_at).toLocaleString('en-GB')} · {job.passenger_name} · {job.passengers} passenger(s)</p><p>{job.large_bags} large and {job.small_bags} small bags · {job.fleet_tier}</p><p className="driver-payment">Your agreed payment: <b>£{Number(job.driver_agreed_payment).toFixed(2)}</b> · {statusLabel(job.payment_status)}</p>{job.notes && <p>{job.notes}</p>}<div className="driver-job-actions">{job.phone && !['OFFERED','DRIVER_DECLINED','ASSIGNMENT_CANCELLED','CUSTOMER_CANCELLED'].includes(job.assignment_status) && <><a href={`tel:${job.phone}`}>Call customer</a><a href={`sms:${job.phone}`}>SMS customer</a></>}<JobActions job={job} refresh={refresh} /></div></article>)}</div>;
}
function JobActions({ job, refresh }: { job: Job; refresh: () => Promise<void> }) {
  const actions: Record<string, [string,string][]> = { OFFERED: [['ACCEPT','Accept offer'],['DECLINE','Decline']], ASSIGNED: [['EN_ROUTE','Mark en route']], EN_ROUTE: [['ARRIVED','Mark arrived']], ARRIVED: [['ONBOARD','Passenger onboard'],['NO_SHOW','Report no-show']], PASSENGER_ONBOARD: [['COMPLETE','Complete journey']] };
  async function act(action: string) { const needsNote = ['DECLINE','NO_SHOW','INCIDENT','ASSISTANCE'].includes(action); const note = needsNote ? prompt(action === 'ASSISTANCE' ? 'What assistance do you need?' : 'Please provide details:') : ''; if (needsNote && !note) return; const response = await fetch('/api/driver-actions', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ assignmentId: job.assignment_id, action, note }) }); const value = await response.json() as { error?: string }; if (!response.ok) { alert(value.error || 'Action failed'); return; } await refresh(); }
  return <>{(actions[job.assignment_status] || []).map(([action,label]) => <button key={action} onClick={() => void act(action)}>{label}</button>)}{['ACKNOWLEDGED','ASSIGNED','EN_ROUTE','ARRIVED','PASSENGER_ONBOARD'].includes(job.assignment_status) && <><button onClick={() => void act('INCIDENT')}>Report incident</button><button onClick={() => void act('ASSISTANCE')}>Request Admin help</button></>}</>;
}

function DriverCalendar({ jobs, refresh }: { jobs: Job[]; refresh: () => Promise<void> }) {
  const [month, setMonth] = useState(() => new Date()); const [selected, setSelected] = useState(new Date().toISOString().slice(0,10)); const year = month.getFullYear(); const index = month.getMonth(); const days = new Date(year,index+1,0).getDate(); const offset = (new Date(year,index,1).getDay()+6)%7;
  const byDay = useMemo(() => new Map(Array.from({ length: days },(_,i) => { const key = `${year}-${String(index+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`; return [key,jobs.filter((job) => job.pickup_at.slice(0,10)===key)]; })),[jobs,days,index,year]);
  return <section className="driver-card"><div className="driver-calendar-head"><button onClick={() => setMonth(new Date(year,index-1,1))}>← Previous</button><h2>{month.toLocaleDateString('en-GB',{month:'long',year:'numeric'})}</h2><button onClick={() => setMonth(new Date(year,index+1,1))}>Next →</button></div><div className="driver-calendar">{Array.from({length:offset},(_,i)=><i key={`blank-${i}`} />)}{Array.from(byDay.entries()).map(([date,dayJobs]) => <button key={date} className={selected===date?'selected':''} onClick={() => setSelected(date)}><b>{Number(date.slice(-2))}</b>{dayJobs.map((job)=><small key={job.assignment_id}>{new Date(job.pickup_at).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})} {job.pickup}</small>)}</button>)}</div><h3>Daily view · {new Date(`${selected}T12:00:00`).toLocaleDateString('en-GB',{dateStyle:'full'})}</h3><JobList jobs={byDay.get(selected)||[]} refresh={refresh} /></section>;
}
function AvailabilityView({ entries, refresh }: { entries: Availability[]; refresh: () => Promise<void> }) {
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form=event.currentTarget; const data=new FormData(form); const response=await fetch('/api/driver-availability',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({date:data.get('date'),fullDay:data.get('fullDay')==='on',startTime:data.get('startTime'),endTime:data.get('endTime'),reason:data.get('reason')})}); if(!response.ok){const value=await response.json() as {error?:string};alert(value.error||'Could not save availability');return;} form.reset(); await refresh(); }
  async function remove(id:number){await fetch(`/api/driver-availability?id=${id}`,{method:'DELETE'});await refresh();}
  return <section className="driver-card"><h2>Availability</h2><p>Record times when you cannot receive new offers. Existing assignments are not automatically cancelled.</p><form className="driver-availability-form" onSubmit={submit}><label>Date<input name="date" type="date" required /></label><label className="check-label"><input name="fullDay" type="checkbox" defaultChecked />Full day</label><label>Start<input name="startTime" type="time" /></label><label>End<input name="endTime" type="time" /></label><label>Reason<input name="reason" /></label><button>Save unavailable period</button></form><div className="driver-table">{entries.map((entry)=><div key={entry.id}><span>{entry.unavailable_date}</span><b>{entry.full_day?'Full day':`${entry.start_time}–${entry.end_time}`}</b><em>{entry.reason||'Unavailable'}</em><button onClick={()=>void remove(entry.id)}>Remove</button></div>)}</div></section>;
}
function ComplianceView({ profile }: { profile: Workspace['profile'] }) { const reasons=profile?.eligibility_reasons||[]; return <section className="driver-card"><h2>My compliance status</h2>{reasons.length?<div className="driver-alert"><b>Not currently eligible for new assignments</b><ul>{reasons.map((reason)=><li key={reason}>{reason}</li>)}</ul></div>:<p className="driver-success">All mandatory records are current and assignment approval is active.</p>}<dl className="driver-profile"><div><dt>PHV Driver licence expiry</dt><dd>{String(profile?.private_hire_licence_expiry||'Missing')}</dd></div><div><dt>DVLA status valid until</dt><dd>{String(profile?.dvla_licence_expiry||'Missing')}</dd></div><div><dt>MOT expiry</dt><dd>{String(profile?.mot_expiry||'Missing')}</dd></div><div><dt>Insurance expiry</dt><dd>{String(profile?.insurance_expiry||'Missing')}</dd></div><div><dt>Vehicle PHV licence expiry</dt><dd>{String(profile?.private_hire_vehicle_licence_expiry||'Missing')}</dd></div><div><dt>V5</dt><dd>{String(profile?.v5_document_status||'Missing')}</dd></div></dl></section>; }
