import { env } from 'cloudflare:workers';
import { NextResponse } from 'next/server';
import { getPortalPrincipal } from '../../portal-auth';
import { validMutationOrigin } from '../../request-security';

async function admin(){const user=await getPortalPrincipal();return user?.role==='OWNER_ADMIN'?user:null}
async function owns(user:NonNullable<Awaited<ReturnType<typeof admin>>>,type:string,id:string){if(type==='DRIVER')return env.DB.prepare('SELECT id FROM driver_profiles WHERE id=? AND organisation_id=? AND owner_id=?').bind(id,user.organisationId,user.ownerId).first();if(type==='VEHICLE')return env.DB.prepare('SELECT id FROM driver_vehicles WHERE id=? AND organisation_id=? AND owner_id=?').bind(id,user.organisationId,user.ownerId).first();return null}

export async function GET(req:Request){const user=await admin();if(!user)return NextResponse.json({error:'Access denied'},{status:403});const url=new URL(req.url),type=String(url.searchParams.get('entityType')||''),id=String(url.searchParams.get('entityId')||'');if(!await owns(user,type,id))return NextResponse.json({error:'Profile not found'},{status:404});const rows=await env.DB.prepare('SELECT id,entity_type,entity_id,field_name,file_name,content_type,uploaded_at FROM profile_documents WHERE organisation_id=? AND entity_type=? AND entity_id=? ORDER BY uploaded_at DESC').bind(user.organisationId,type,id).all();return NextResponse.json(rows.results)}
export async function POST(req:Request){if(!validMutationOrigin(req))return NextResponse.json({error:'Invalid request origin'},{status:403});const user=await admin();if(!user)return NextResponse.json({error:'Access denied'},{status:403});const form=await req.formData(),file=form.get('file'),type=String(form.get('entityType')||''),id=String(form.get('entityId')||''),field=String(form.get('fieldName')||'compliance').slice(0,80);if(!await owns(user,type,id))return NextResponse.json({error:'Profile not found'},{status:404});if(!(file instanceof File)||!file.size||file.size>2_000_000||!['application/pdf','image/jpeg','image/png'].includes(file.type))return NextResponse.json({error:'PDF, JPG or PNG up to 2 MB required'},{status:400});const bytes=new Uint8Array(await file.arrayBuffer()),name=file.name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,180),key=`${user.ownerId}/profiles/${type.toLowerCase()}/${id}/${crypto.randomUUID()}-${name}`;await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:file.type},customMetadata:{originalName:name,uploadedBy:user.email}});const result=await env.DB.prepare('INSERT INTO profile_documents(owner_id,organisation_id,entity_type,entity_id,field_name,file_name,content_type,object_key,uploaded_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(user.ownerId,user.organisationId,type,id,field,name,file.type,key,new Date().toISOString()).run();return NextResponse.json({id:result.meta.last_row_id},{status:201})}
export async function DELETE(req:Request){if(!validMutationOrigin(req))return NextResponse.json({error:'Invalid request origin'},{status:403});const user=await admin();if(!user)return NextResponse.json({error:'Access denied'},{status:403});const id=Number(new URL(req.url).searchParams.get('id'));const row=await env.DB.prepare('SELECT id,object_key FROM profile_documents WHERE id=? AND organisation_id=? AND owner_id=?').bind(id,user.organisationId,user.ownerId).first<{id:number;object_key:string}>();if(!row)return NextResponse.json({error:'Document not found'},{status:404});await env.BUCKET.delete(row.object_key);await env.DB.prepare('DELETE FROM profile_documents WHERE id=? AND organisation_id=?').bind(id,user.organisationId).run();await env.DB.prepare('INSERT INTO audit_events(owner_id,actor_email,action,entity_type,entity_id,summary,created_at) VALUES(?,?,?,?,?,?,?)').bind(user.ownerId,user.email,'DELETE_PROFILE_DOCUMENT','profile_document',String(id),'Deleted compliance document',new Date().toISOString()).run();return NextResponse.json({ok:true})}
