import { env } from 'cloudflare:workers';
import { NextResponse } from 'next/server';
import { cloudflareAuthEnabled, getPortalPrincipal } from '../../portal-auth';
import { validMutationOrigin } from '../../request-security';

async function admin(){if(!cloudflareAuthEnabled())return null;const user=await getPortalPrincipal();return user?.role==='OWNER_ADMIN'?user:null}
export async function GET(){const user=await admin();if(!user)return NextResponse.json({error:'Access denied'},{status:403});const rows=await env.DB.prepare(`SELECT a.*,p.full_name,s.email,v.registration,v.vehicle_make,v.vehicle_model FROM driver_vehicle_assignments a JOIN driver_profiles p ON p.id=a.driver_profile_id JOIN portal_staff s ON s.id=p.staff_id JOIN driver_vehicles v ON v.id=a.vehicle_id WHERE a.organisation_id=? AND a.owner_id=? ORDER BY a.active DESC,a.valid_from DESC`).bind(user.organisationId,user.ownerId).all();return NextResponse.json(rows.results)}
export async function POST(req:Request){if(!validMutationOrigin(req))return NextResponse.json({error:'Invalid request origin'},{status:403});const user=await admin();if(!user)return NextResponse.json({error:'Access denied'},{status:403});const body=await req.json() as Record<string,unknown>;const driverProfileId=String(body.driverProfileId||''),vehicleId=String(body.vehicleId||''),validFrom=String(body.validFrom||'');if(!driverProfileId||!vehicleId||!/^\d{4}-\d{2}-\d{2}$/.test(validFrom))return NextResponse.json({error:'Driver, vehicle and valid-from date are required'},{status:400});const driver=await env.DB.prepare('SELECT id FROM driver_profiles WHERE id=? AND organisation_id=? AND owner_id=?').bind(driverProfileId,user.organisationId,user.ownerId).first();const vehicle=await env.DB.prepare('SELECT id FROM driver_vehicles WHERE id=? AND organisation_id=? AND owner_id=?').bind(vehicleId,user.organisationId,user.ownerId).first();if(!driver||!vehicle)return NextResponse.json({error:'Driver or vehicle not found'},{status:404});const now=new Date().toISOString();if(body.primaryVehicle===true)await env.DB.prepare('UPDATE driver_vehicle_assignments SET primary_vehicle=0,updated_at=? WHERE driver_profile_id=? AND organisation_id=?').bind(now,driverProfileId,user.organisationId).run();const result=await env.DB.prepare('INSERT INTO driver_vehicle_assignments(organisation_id,owner_id,driver_profile_id,vehicle_id,valid_from,valid_until,primary_vehicle,active,approved,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(user.organisationId,user.ownerId,driverProfileId,vehicleId,validFrom,String(body.validUntil||''),body.primaryVehicle===true?1:0,body.active===false?0:1,body.approved===true?1:0,now,now).run();await env.DB.prepare('INSERT INTO audit_events(owner_id,actor_email,action,entity_type,entity_id,summary,created_at) VALUES(?,?,?,?,?,?,?)').bind(user.ownerId,user.email,'ASSIGN_DRIVER_VEHICLE','driver_vehicle_assignment',String(result.meta.last_row_id),'Assigned vehicle to Driver profile',now).run();return NextResponse.json({id:result.meta.last_row_id},{status:201})}
export async function PATCH(req:Request){if(!validMutationOrigin(req))return NextResponse.json({error:'Invalid request origin'},{status:403});const user=await admin();if(!user)return NextResponse.json({error:'Access denied'},{status:403});const body=await req.json() as Record<string,unknown>;const id=Number(body.id);if(!Number.isSafeInteger(id))return NextResponse.json({error:'Assignment ID required'},{status:400});const now=new Date().toISOString();await env.DB.prepare('UPDATE driver_vehicle_assignments SET active=?,valid_until=?,updated_at=? WHERE id=? AND organisation_id=? AND owner_id=?').bind(body.active===true?1:0,String(body.validUntil||new Date().toISOString().slice(0,10)),now,id,user.organisationId,user.ownerId).run();return NextResponse.json({ok:true})}
