import { env } from 'cloudflare:workers';
import { getPortalPrincipal } from '../../portal-auth';

const escape = (value: unknown) => String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
export async function GET(req: Request) {
  const user = await getPortalPrincipal(); if (!user || user.role !== 'DRIVER') return new Response('Access denied', { status: 403 });
  const id = Number(new URL(req.url).searchParams.get('assignmentId'));
  const row = await env.DB.prepare(`SELECT a.*,b.passenger_name,b.pickup,b.dropoff,b.pickup_at,b.fare,b.fleet_tier FROM booking_assignments a JOIN bookings b ON b.id=a.booking_id WHERE a.id=? AND a.owner_id=? AND a.driver_staff_id=?`).bind(id,user.ownerId,user.userId).first<Record<string,unknown>>();
  if (!row) return new Response('Receipt not found', { status: 404 });
  if (row.status !== 'COMPLETED' || row.collection_status !== 'COLLECTED') return new Response('A receipt is available only after the journey is completed and collection is recorded.', { status: 409 });
  const receipt = escape(row.receipt_number); const fare = Number(row.fare || 0).toFixed(2);
  const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${receipt}</title><style>@page{size:A4;margin:18mm}body{max-width:720px;margin:30px auto;font-family:Arial,sans-serif;color:#222}header{text-align:center;border-bottom:3px solid #c69b2d;padding:20px}header b{font-size:28px;letter-spacing:.15em}h1{font-size:20px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:15px;margin:24px 0}.grid div,.route{padding:14px;border:1px solid #ddd}.grid small,.route small{display:block;color:#666;text-transform:uppercase;font-size:10px;margin-bottom:5px}.total{display:flex;justify-content:space-between;padding:18px;border-top:2px solid #c69b2d;border-bottom:2px solid #c69b2d;font-size:20px;font-weight:bold}footer{margin-top:24px;color:#666;font-size:11px}button{margin-top:20px;padding:10px 18px}@media print{button{display:none}}</style></head><body><header><b>APX RIDE</b><div>ELEVATE EVERY MILE</div></header><h1>Journey receipt</h1><div class="grid"><div><small>Receipt</small><b>${receipt}</b></div><div><small>Date issued</small><b>${escape(new Date().toLocaleDateString('en-GB'))}</b></div><div><small>Passenger</small><b>${escape(row.passenger_name)}</b></div><div><small>Payment collected</small><b>${escape(row.collection_method)}</b></div></div><div class="route"><small>Journey</small><b>${escape(row.pickup)} → ${escape(row.dropoff)}</b><p>${escape(new Date(String(row.pickup_at)).toLocaleString('en-GB'))} · ${escape(row.fleet_tier)}</p></div><div class="total"><span>Amount received</span><strong>£${fare}</strong></div><footer>This is a journey receipt confirming collection for the completed journey. Formal account invoices are issued by APX RIDE administration.</footer><button onclick="window.print()">Print / save receipt</button></body></html>`;
  return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'private, no-store','content-security-policy':"default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'",'x-content-type-options':'nosniff'}});
}
