import { env } from 'cloudflare:workers';
import { NextResponse } from 'next/server';
import { getPortalAdmin } from '../../portal-auth';
import { validMutationOrigin } from '../../request-security';

async function authorised() { return getPortalAdmin(); }
export async function GET() { const user = await authorised(); if (!user) return NextResponse.json({ error: 'Access denied' }, { status: 403 }); const result = await env.DB.prepare('SELECT * FROM unavailable_periods WHERE owner_id=? ORDER BY unavailable_date').bind(user.userId).all(); return NextResponse.json(result.results); }
export async function POST(req: Request) { if(!validMutationOrigin(req))return NextResponse.json({error:'Invalid request origin'},{status:403}); const user = await authorised(); if (!user) return NextResponse.json({ error: 'Access denied' }, { status: 403 }); const body = await req.json() as { startDate?: string; endDate?: string; startTime?: string; endTime?: string; reason?: string }; const start=String(body.startDate||''),end=String(body.endDate||''),startTime=String(body.startTime||''),endTime=String(body.endTime||''); if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end)||end<start||!/^\d{2}:\d{2}$/.test(startTime)||!/^\d{2}:\d{2}$/.test(endTime)||(start===end&&endTime<=startTime))return NextResponse.json({error:'Enter a valid start/end date and time range'},{status:400}); const result = await env.DB.prepare('INSERT INTO unavailable_periods(owner_id,unavailable_date,unavailable_until,full_day,start_time,end_time,reason,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(user.userId,start,end,0,startTime,endTime,String(body.reason||'').slice(0,300),new Date().toISOString()).run(); return NextResponse.json({ id: result.meta.last_row_id }, { status: 201 }); }
export async function DELETE(req: Request) { if(!validMutationOrigin(req))return NextResponse.json({error:'Invalid request origin'},{status:403}); const user = await authorised(); if (!user) return NextResponse.json({ error: 'Access denied' }, { status: 403 }); const id = Number(new URL(req.url).searchParams.get('id')); await env.DB.prepare('DELETE FROM unavailable_periods WHERE id=? AND owner_id=?').bind(id, user.userId).run(); return NextResponse.json({ ok: true }); }
