import { env } from 'cloudflare:workers';
import { headers } from 'next/headers';
import { NextResponse } from 'next/server';
const schema=`CREATE TABLE IF NOT EXISTS bookings (id INTEGER PRIMARY KEY AUTOINCREMENT, owner_id TEXT NOT NULL, passenger_name TEXT NOT NULL, phone TEXT NOT NULL DEFAULT '', pickup TEXT NOT NULL, dropoff TEXT NOT NULL, pickup_at TEXT NOT NULL, operator TEXT NOT NULL DEFAULT 'APX RIDE', passengers INTEGER NOT NULL DEFAULT 1, large_bags INTEGER NOT NULL DEFAULT 0, small_bags INTEGER NOT NULL DEFAULT 0, fleet_tier TEXT NOT NULL DEFAULT 'Saloon', distance REAL NOT NULL DEFAULT 0, fare REAL NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'upcoming', notes TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`;
const owner=async()=>(await headers()).get('oai-authenticated-user-id')||'local-preview-owner';
async function ready(){await env.DB.prepare(schema).run();await env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_bookings_owner_pickup ON bookings(owner_id, pickup_at)').run()}
export async function GET(){await ready();const id=await owner();const data=await env.DB.prepare('SELECT * FROM bookings WHERE owner_id=? ORDER BY pickup_at DESC').bind(id).all();return NextResponse.json(data.results)}
export async function POST(req:Request){await ready();const id=await owner(),b=await req.json() as Record<string,unknown>,now=new Date().toISOString();const r=await env.DB.prepare(`INSERT INTO bookings(owner_id,passenger_name,phone,pickup,dropoff,pickup_at,operator,passengers,large_bags,small_bags,fleet_tier,distance,fare,status,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,b.passengerName||'Unnamed passenger',b.phone||'',b.pickup||'',b.dropoff||'',b.pickupAt||now,b.operator||'APX RIDE',b.passengers||1,b.largeBags||0,b.smallBags||0,b.fleetTier||'Saloon',b.distance||0,b.fare||0,b.status||'upcoming',b.notes||'',now,now).run();return NextResponse.json({id:r.meta.last_row_id},{status:201})}
export async function PATCH(req:Request){await ready();const id=await owner(),b=await req.json() as {id:number,status:string};await env.DB.prepare('UPDATE bookings SET status=?,updated_at=? WHERE id=? AND owner_id=?').bind(b.status,new Date().toISOString(),b.id,id).run();return NextResponse.json({ok:true})}
export async function DELETE(req:Request){await ready();const id=await owner(),url=new URL(req.url);await env.DB.prepare("UPDATE bookings SET status='archived',updated_at=? WHERE id=? AND owner_id=?").bind(new Date().toISOString(),Number(url.searchParams.get('id')),id).run();return NextResponse.json({ok:true})}
